# Generated by Django 4.1.4 on 2022-12-10 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'verbose_name_plural': 'Quizes'},
        ),
    ]
