# Generated by Django 4.1.4 on 2022-12-10 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_alter_answer_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={},
        ),
    ]
