# Generated by Django 4.1.4 on 2022-12-10 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('theme', models.CharField(max_length=200)),
                ('questions_amount', models.IntegerField()),
                ('time', models.IntegerField(help_text='Отведенное время в минутах')),
                ('score', models.IntegerField(help_text='Счет в процентах')),
            ],
        ),
    ]
