# Generated by Django 4.1.4 on 2022-12-10 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={'verbose_name_plural': 'Quizes'},
        ),
        migrations.RenameField(
            model_name='quiz',
            old_name='score',
            new_name='score_to_pass',
        ),
    ]
